# Generated by Django 4.1.6 on 2023-02-10 22:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
