# Generated by Django 4.1.6 on 2023-02-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'M'), ('Feminino', 'F'), ('Prefiro nao informar', 'PNI')], default='PNI', max_length=20),
        ),
    ]
