# Generated by Django 4.1.6 on 2023-02-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_score'),
        ('usuario', '0003_alter_usuario_nome_alter_usuario_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comprar',
            new_name='Compra',
        ),
    ]
