# Generated by Django 4.1.6 on 2023-02-12 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('score', models.IntegerField(max_length=20)),
                ('nome_imagem', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
